services:
  adyl-creation-api:
    container_name: adyl-creation-api
    build:
      context: .
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8084}:${SERVER_PORT:-8084}"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./data/photos:/data/photos
    networks:
      - adyl-creation-network

networks:
  adyl-creation-network:
    external: true