services:
  adyl-creation-api:
    container_name: adyl-creation-api
    build:
      context: .
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8084}:${SERVER_PORT:-8084}"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - photos_data_adyl_creation:/data/photos
    networks:
      - adyl-creation-network

volumes:
  photos_data_adyl_creation:

networks:
  adyl-creation-network:
    external: true